version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./env/.env
  api:
    container_name: posts-api
    build:
      context: ./
    image: posts-api
    depends_on:
      - postgres
    ports:
      - 3001:3001
    env_file:
      - ./env/.env
    links:
      - postgres
    volumes:
      - ./:/src
      - /src/node_modules
volumes:
  progres:
    driver: local


